FROM fedora

RUN yum install -y golang make
ENV GOPATH=/go
RUN mkdir -p /go/src/kubevirt.io/vmctl/cmd/vmctl
RUN mkdir -p /go/src/kubevirt.io/vendor
COPY . /go/src/kubevirt.io/vmctl/

WORKDIR /go/src/kubevirt.io/vmctl/pkg
RUN go test -cover -v -race ./... 2>&1 | tee /output/output.txt
