#!/bin/sh

set -x

VMNAME=$1
INSTANCENAME=$VMNAME-$HOSTNAME

KUBECTL=$(ls -1 /kubectl*)
VIRTCTL=$(ls -1 /virtctl*)

trap "$KUBECTL delete vm $INSTANCENAME" EXIT

# Start it to have a VM reference
$VIRTCTL start $VMNAME

cat > vmToPodAffinity <<EOF
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        topologyKey: 'kubernetes.io/hostname'
        labelSelector:
          matchLabels:
            guest: $VMNAME
EOF

# Create a copy of the VM with generate name
$KUBECTL get vm $VMNAME -o yaml \
  | sed "/^  name:/ s/name:.*/name: $INSTANCENAME/" \
  | sed "/^spec:/ r vmToPodAffinity" \
  | tee \
  | $KUBECTL apply -f -

sleep inf
