#!/bin/sh

#. /podinfo/annotations

set -x

VMNAME=$1
INSTANCENAME=$VMNAME-$RANDOM
KUBECTL=$(ls -1 /kubectl*)
VIRTCTL=$(ls -1 /virtctl*)

trap "$KUBECTL delete vm $INSTANCENAME" EXIT

# Start it to have a VM reference
$VIRTCTL start $VMNAME

# Create a copy of the VM with generate name
$KUBECTL get vm $VMNAME |\
  | sed "/^  name:/ s/name:.*/name: $INSTANCENAME/" \
  | kubectl apply -f -

sleep inf
