#!/bin/bash

PROTOTYPEVMNAME=$1
INSTANCENAME=$PROTOTYPEVMNAME-$HOSTNAME

KUBECTL=$(ls -1 kubectl* || which kubectl)
VIRTCTL=$(ls -1 virtctl* || which virtctl)

trap "$KUBECTL delete --grace-period=0 vm $INSTANCENAME" EXIT

# Get the prototype
$KUBECTL get vm $PROTOTYPEVMNAME -o json | tee prototype.json

# Modify prototype
js derive_vm.js prototype.json $INSTANCENAME | tee instance.json

# Create VM
$KUBECTL apply -f instance.json

$KUBECTL get -o yaml ovm $INSTANCENAME

sleep inf
