#!/bin/bash

set -ex
echo PWD $PWD

VMCTLDIR=$(dirname $0)

PROTOTYPEVMNAME=$1
VMCTLVM=$PROTOTYPEVMNAME-$HOSTNAME

KUBECTL=${KUBECTL:-$(which kubectl)}
VIRTCTL=${VIRTCTL:-$(which virtctl)}

trap "$KUBECTL delete vm $VMCTLVM" EXIT

cd $VMCTLDIR

# Get the prototype, derive a new vm, create it
$KUBECTL get vm $PROTOTYPEVMNAME -o json > prototype.json
js derive_vm.js prototype.json $VMCTLVM \
  | $KUBECTL apply -f -

$KUBECTL get -o yaml vm $VMCTLVM

sleep inf
