#!/bin/bash

set -ex
echo PWD $PWD

VMCTLDIR=$(dirname $0)

PROTOTYPEVMNAME=$1
VMCTLVM=$PROTOTYPEVMNAME-$HOSTNAME

KUBECTL=${KUBECTL:-$(which kubectl)}
VIRTCTL=${VIRTCTL:-$(which virtctl)}

trap "$KUBECTL delete --grace-period=0 vm $VMCTLVM" EXIT

# Get the prototype
$KUBECTL get vm $PROTOTYPEVMNAME -o json | tee $VMCTLDIR/prototype.json

# Modify prototype
js $VMCTLDIR/derive_vm.js prototype.json $VMCTLVM | tee $VMCTLDIR/instance.json

# Create VM
$KUBECTL apply -f $VMCTLDIR/instance.json

$KUBECTL get -o yaml vm $VMCTLVM

sleep inf
