#!/bin/bash

set -ex
echo PWD $PWD

VMCTLDIR=$(dirname $0)

PROTOTYPEVMNAME=$1
VMCTLVM=$PROTOTYPEVMNAME-$HOSTNAME

KUBECTL=${KUBECTL:-$(which kubectl)}
VIRTCTL=${VIRTCTL:-$(which virtctl)}

trap "$KUBECTL delete vm $VMCTLVM" EXIT

cd $VMCTLDIR

PODNAME=$(cat /etc/podinfo/name)
VMCTLNODENAME=$($KUBECTL get pod $PODNAME -o jsonpath="{.spec.nodeName}")

# Get the prototype, derive a new vm, create it
$KUBECTL get vm $PROTOTYPEVMNAME -o json > prototype.json
js derive_vm.js prototype.json $VMCTLVM $VMCTLNODENAME \
  | tee /dev/stderr \
  | $KUBECTL apply -f -

$KUBECTL get -o yaml vm $VMCTLVM

sleep inf
